[server]
    addr = "0.0.0.0:1124"
    locale = "zh"

[app]
    name="reminder_app"
    debug= true
    version="v0.1.0"

[mysql.main]
    tablePrefix = "reminder"
    host = "127.0.0.1"
    username = "root"
    password = "root"
    dbName = "reminder_app"
    type = "mysql"
    debug = true

[rpc]
    etcd_addr="127.0.0.1:2380"
    ip="0.0.0.0"
    port=8484
    register_ttl="10s"
    register_interval="3s"

[xlog]
    name = "reminder_app.log"
    dir = "."
    level = ""
    async = false
    debug = true
    add_caller= true
    caller_skip=2

[app.govern]
    host = "127.0.0.1"
    port = 4569

