server:
  addr: 0.0.0.0:12345
  locale: zh
database:
  host: 127.0.0.1
  username: root
  password: root
  dbName: reminder
  type: mysql
  debug: true
reminder:
  Spec:
    - "@daily"
rabbitMQ:
  host:
  username:
  password:
  port: 5672
  name: reminderMQ
email:
  host: smtp.yeah.net
  username: yangzzzzzz@yeah.net
  password:
  port: 465
wxApp:
  appId:
  secret:
log:
  level: info
  development: false
  httpServer:
    open: true
    addr: 0.0.0.0:9000
  outputPaths:
    - "log.log"
  errorOutputPaths:
    - "err.log"
