server:
  addr: 0.0.0.0:12345
  locale: zh
database:
  host: 127.0.0.1
  username: root
  password: root
  dbName: reminder
  type: mysql
  debug: true
reminder:
  Spec:
    - "* * * * *"
rabbitMQ:
  host: 127.0.0.1
  username: admin
  password: admin
  port: 5672
  name: reminderMQ