apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: reminder
spec:
  selector:
    matchLabels:
      name: app
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        name: app
        version: v1
    spec:
      containers:
      - name: reminder-app
        image: "{{index .Values.images 0}}:{{.Values.version}}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80