apiVersion: v1
kind: Service
metadata:
  name: k8s-reminder-server-app
  namespace: reminder
spec:
  type: NodePort
  selector:
    name: app
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 80 

